### ISSUE TITLE
Self Expiring Store Items

### ISSUE THREAD

**Issue by joe-l-bright** [toranb/ember-cli-simple-store#11]
I would like to add the below code to this project so store items can be managed internally.
This is like bread in a grocery store, the bread comes with an expiration date and the store will pull the bags off the shelf if they are expired.  I was hoping we could do the same concept in here. :)

``` javascript
function buildRecord(type, data, store) {
    var containerKey = "model:" + type;
    var factory = store.container.lookupFactory(containerKey);

    Ember.assert("No model was found for type: " + type, factory);

    var record = factory.create(data);
    var id = data.id;
    identityMapForType(type, store)[id] = record;
    arrayForType(type, store).pushObject(record);
------------ diff ----------------
    if(data.expire) {
        Ember.run.later(function() {
            delete identityMapForType[type][record.id];
            arrayForType(type, store).removeObject(record);
        }, data.expire);
    }
------------ diff ----------------
    return record;
}
```

**Comment by joe-l-bright** [comment]
btw... this is not an issue.  I just wanted to get your thoughts :)

**Comment by toranb** [comment]
I like the idea of unloading objects (as the apps memory usage will only grow over time as we never refresh the full page anymore). The challenge is how do you know it's "safe" or "a good time" to expire and unload those items? For example

1) the first item I pushed in will expire in 10 minutes
2) later I'm on a page (list of items) and that first item is on the page
3) I don't do anything on that page for 9:59 and suddenly the expire happens (the page changes because that item is removed/deleted w/out any action from the user or the server)

I'd expect we would need to know more (context is key) before simply removing something. I don't know if the store (as it's the lowest level primitive here) should know /will have enough information to know when we could truly expire/unload objects. I imagine an object higher up in the stack would know when/or if it's safe to unload.

The repository/controller or route could do this manually when it's a good time

ie- if you are loading a page of objects and you don't get a "new" version of that first record (and that first record isn't showing from what the route knows about it's context) so you unload it for the moment. If later you pull that in (again) with an XHR you just add it back to the store.

**Comment by williamsbdev** [comment]
@joe-l-bright I think this could be a nice feature for a host app to introduce. These are my thoughts on this:
- I don't think it should be the responsibility of the store.
  - I believe the store should have as few opinions as possible
  - It already has the opinion that every object should have an id
- Expecting an object to optionally have an expire key and that it always means that is the time-to-live of the object is (in my opinion) a dangerous precedent
- I like the idea and think the host app could have a wrapper for the store to do this
- I had not thought about what @toranb mentioned where all the sudden, an object disappears from the list because it's time-to-live is up. That could/would be a very real and undesired scenario.

**Comment by joe-l-bright** [comment]
keep in mind this expiration is not determined by the store.  Its determined up in stack.  Just like the bread example.  Only things that have intended expirations will expire.  The time is all determined by "users" of the store.  If a user wants to have a predetermined time allowed for an item, it sets an expire=5000 before adding to store.  The store then respects that time and removes it.  This is geared towards 'messages' items and wouldn't likely apply to XHR items.

**Comment by joe-l-bright** [comment]
thanks for thinking on this gentlemen :+1:    closing out and searching for alt route.
