### ISSUE TITLE
v3.6.0 upgrade guide (breaking change)

### ISSUE THREAD

**Issue by toranb** [toranb/ember-cli-simple-store#41]
If you are upgrading from v3.5.0 or v4.0.0-beta.5 one thing to note is that we've renamed the initializer so people can use this along side ember-data. This didn't break any behavior directly but one change I've seen a few people are required to make is that if you had a custom initializer in your app and wanted it to run "after" the initializer that ships w/ this addon you would reference it by name like so

``` js
export function initialize() {
    var application = arguments[1] || arguments[0];
    //do stuff here
}

export default {
    name: 'repositories',
    after: 'store',
    initialize: initialize
};
```

In the v3.6.0 release this was renamed so be sure to update the name you see in after (like below)

``` js
export function initialize() {
    var application = arguments[1] || arguments[0];
    //do stuff here
}

export default {
    name: 'repositories',
    after: 'simple-store',
    initialize: initialize
};
```

**Comment by toranb** [comment]
A quick note: although this was a breaking change it shouldn't be a terrible upgrade (commit below is an example from v3.4 => v3.6)

https://github.com/toranb/ember-2-skeleton-app/commit/35b8d04d05833874b931e4d49c39a43fcc9701b0

**Comment by williamsbdev** [comment]
@toranb thank you for this upgrade guide. Unfortunately, we did not abide by semantic versioning here. When upgrading a minor version, only new opt-in features should be introduced. This was a breaking API change.

I've been looking through the source for master and noticed that this is completely removed in favor of injecting the store as a service. I hope and request that the next release goes to 4.0.

Additionally, for future releases, let's do our best to ensure semantic versions so that consumers can rely on upgrading in the current series they are using without impact to current APIs.

Thanks!

**Comment by toranb** [comment]
@williamsbdev  Just a quick note: what you see on master now is v4 only (the last release of the v3 series is v3.6.0)

Sorry for the breaking name change. As you mentioned, this should have waited until v4.0.0 stable was released.
