### ISSUE TITLE
Question: Destroy Objects on Clear

### ISSUE THREAD

**Issue by benkiefer** [toranb/ember-cli-simple-store#54]
Quick question. Is there any reason why removing an object from the store or clearing the store (by type or full-on nuclear clear) does not destroy the object(s) being removed?

For example, I have an object that periodically calls notifyPropertyChange to update a remaining time on itself; however, when that object is removed from the store (what I would consider a "delete"), it does not call the destroy method on the object, which means that timer keeps executing until the app is destroyed.

**Comment by toranb** [comment]
That's a great question ... looking at the api it's clear the "create" is adding objects to the store but also creating the ember object itself.

So in the destory/remove apis I assume we should invoke destroy on the given object/or objects

Anything else we should think through here before hacking into the code?

**Comment by toranb** [comment]
One question I thought of this morning is related to versioning after this change. Is the feature you describe a "breaking api" in some way to someone using the project? If not, we could patch the 3/4 series of this addon. If it is decided to be a real break it's likely we would need to release something like this in a 5x

What alternative approach exists now without this change? You delete each object yourself after remove/ or clear is called on the store?

**Comment by benkiefer** [comment]
Completely agree that this is a breaking change. A 5.x seems like the right way to go.

**Comment by toranb** [comment]
@snewcomer @jasonmit @aquamme @thoov you guys have any questions about the work @benkiefer is asking about here? On the surface it seems to be a fairly straight forward change and in my view it's about consistency because the `push` api will create an object _and_ add it to the store yet `clear` only drops the reference to each (not removing them/calling destroy).

This would be a 5x feature as it's a big shift in behavior from 3x/4x today. If you think of anything we should consider before taking this on please let me know so we can discuss it further :)

**Comment by snewcomer** [comment]
Wouldn't hurt us! 

I'm sure you have everything you need to do this, and if you do, no worries and can probably ignore below....i'll just look at the commit when it is done.  But just from my stream of consciousness and NOT knowing how `notifyPropertyChange` works....

This line should remove any ref and clear out that type in the identityMap object but is up to the garbage collector to remove the lower level objects, right?
https://github.com/toranb/ember-cli-simple-store/blob/cfa03e6f1dc2c8b04324ee826055fd9a3918a266/addon/store.js#L64

This line (https://github.com/toranb/ember-cli-simple-store/blob/cfa03e6f1dc2c8b04324ee826055fd9a3918a266/addon/store.js#L65) calls some `replace` function (not sure where from) but looks like it just swaps out the elements of the array for an empty array (https://github.com/emberjs/ember.js/blob/v2.6.0/packages/ember-runtime/lib/mixins/mutable_array.js#L85).

Is it possible to remove and destroy the lower level objects in order to call `notifyPropertyChange`?  Do you have to loop through the object who's key is the `type` and delete the lower level objects as well until they have no more references?  `idMap: {person: {1: Class, 2: Class}}`

**Comment by toranb** [comment]
@snewcomer I haven't thought through all the implementation details yet but I assume we will need to remove each object in the array/identity map and then flush the filtersMap to free each object so the garbage collector can do its job.

When I dive into the work I can sync up with you to better understand your notifyPropertyChange question. Do you have a test case that better describes the setup/ your action and the expectation of the state after that action to help me think through it?

**Comment by snewcomer** [comment]
@toranb I guess what I was wondering was how to do remove bindings/observers for an object to not only just drop its reference (i.e. manual garbage collection, right??)....But it seems as you mentioned, that calling `destroy` from the Ember API might be the simple sol'n.  Didn't know that existed!

https://ember-twiddle.com/eefa21f4f6b0a24cca6fd5b6eeaa5aa2?openFiles=components.destroy-method.js%2C

**Comment by jasonmit** [comment]
>  you guys have any questions about the work

It seems fine to me, but if you go in this direction then I suspect `remove` should also destroy the record.

**Comment by thoov** [comment]
Agree with what everyone here is saying. Push / Remove should be inverses of each other and thus should destroy the object.

> I haven't thought through all the implementation details yet but I assume we will need to remove 
> each object in the array/identity map and then flush the filtersMap to free each object so the garbage 
> collector can do its job

Seems like [WeakMaps](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap) might be worth looking into instead of having to manually care about the GC.

**Comment by toranb** [comment]
@thoov @snewcomer @jasonmit thanks for the feedback guys - the weakmaps idea may not be required if we just teardown the record, unless I missed something - totally up to be wrong and corrected on this one :)

I'm wrapping up a week of teaching 5th grade kids python and I've got one prior open source commitment pending for early next week but I plan to give this a look late next week! Thanks for all the input

**Comment by toranb** [comment]
Likely bumping this to early next week now :) had some higher priority issues on other OSS projects this week that are pushing me back a few days

**Comment by snewcomer** [comment]
@toranb I think you are right.  Using WeakMaps, the gc will just remove the entry from the WeakMaps, but you still have to destroy the lower level objects anyways for this to happen and to call `notifyPropertyChange`.
