### ISSUE TITLE
Proposal: new method to update

### ISSUE THREAD

**Issue by pixelhandler** [toranb/ember-cli-simple-store#66]
During re-render components already have references to models in the store. `push` may update (set) props on those objects which then redraw. 

Proposal: `push` can replace the reference instead of update (set props) on existing (referenced in DOM) models. And `update` can set props, e.g. perhaps after a form change and persisting that data. 

Impact: since `push` would replace a model reference in the store, models that are passed into components would not re-render until the component re-receives a new model instance. `update` could be used to intentionally set props on an model that is already presented onscreen.

Here is a branch with an example of this change: https://github.com/toranb/ember-cli-simple-store/compare/master...pixelhandler:store-update

Need to test out this theory with models that also have relationships that exist in the store and in the DOM.

Alternatively, a `replace` method could be used to only replace, leaving `push` as it is today (create or update/setProperties)

**Comment by pixelhandler** [comment]
@snewcomer Let's try out this tomorrow.

**Comment by jasonmit** [comment]
Can you go more into the reasons driving this proposal?  For my own curiosity mainly, but might help @toranb and others as well.

**Comment by snewcomer** [comment]
@jasonmit so what we are seeing in 2.10 is that an already rendered child component of a route will update itself before finishing the route model hook.  So our case is:

1.  Render index route then after render click sort (which changes a query params w/ refreshModel: true)
2. Model hook is executed, sends off xhr, xhr comes back and we deserialize the data (store.push).  Let's say a people grid has a role, fullname, and status.  There are multiple `store.push's` going on in the deserialization of the data due to relationships.
3.  Child component has a reference to a complex object and says, ok something in my complex object has changed, let me re-render (Glimmer 2 updating VM?).  This update happens before I deserialized ALL of the data, which results in some empty grid cells, let's say the status column.
4.  Resolve model hook and call setupController, finally passing off the model to the controller.

The exact reason this behavior changed b/w 2.9.1 and 2.10 is something I haven't found other than it's just Glimmer 2 and has two VM's to manage rendering and updating.

So as you probably know [here](https://github.com/toranb/ember-cli-simple-store/blob/master/addon/store.js#L186) we are getting the store's [array property](https://github.com/toranb/ember-cli-simple-store/blob/master/addon/store.js#L32) which is the reference the child component is holding onto.  

The solution to us seems either **1. App specific** - Optimistic rendering (don't wait for model hook to resolve it's promise and just render right away and update the data behind the scenes w/ simple store filters) or **2.  Simple Store specific** - take a more functional approach to the data returned from a `find` / `push` method so the child component doesn't update as the objects it's receiving are different references.

**Comment by pixelhandler** [comment]
@jasonmit The current behavior of the store's find methods return an array that is constant (once created always present). So, an index route's template has a model (the array for type) that is a collection of models. On query param changes that refreshModel on the same route, the model is the same array returned earlier (but may containing different models) Hence a re-render happens after model hook resolves (prior to setupController). Ideally there could be an option to always get a new array from store's find methods. Also, store push could also create a new copy to replace a model instance while update could setup properties on an existing model instance.

**Comment by toranb** [comment]
@pixelhandler @snewcomer 

In reply to your first comment I want to say that I'm not interested in altering the behavior of push for a few reasons

1. The original use case was designed to return a single reference that would act like a constant. This allowed me to unlock optimistic rendering before it was talked about much in the ember community.

2. Because this would break existing apps we would need to ship a 6x and I don't know if that is truly required or desired by a large number of users.

3. Instead (if it's possible) I'd like to consider a new api called `replace` or something equivalent that works with the non optimistic + glimmer 2 approach you described above.

The reason I didn't reply right away is that I wanted to see if you could both take a run at this new api and confirm it solves the problem you've run up against without any other edge cases to consider. As I haven't hit this scenario myself I'd need you both to take the lead on this.

If you are able to spike something out that solves this as you've described, can we continue the discussion as part of a formal pull request?

**Comment by snewcomer** [comment]
Still not sure there is an approach to solve every case.  We had a specific case that was easily solved with less relationships in the grid, i.e. straight json.  If somebody has heavy relationships in a grid view and runs into this same problem, then that is one consideration.  Another is optimistic rendering.  The biggest issue being that even if we call `replace`, `find` will still return a reference that a component can hold onto.  `find` would have to work in concert to return a new array every time and `replace` would over-ride the constant in the store and return that out.

**Comment by pixelhandler** [comment]
@toranb closing this one. We found a scenario using lists where optimistic rendering isn't ideal for records that have various relationships. In that case simply providing a new array of items or plain JS objects can be used. It seems that Simple Store is designed primarily for optimistic rendering in that the array for the resource type is constant.

For this use case we needed to use a new array (not the constant one) to avoid optimistic rendering; that is… while preforming updates like setting up relations for items in a list. 

When a list is filtered via query params in a list route, having the screen re-paint straight away (and prior to the normal route hook completion from `beforeModel` through `setupController`) introduced side effects and a broken UI. Again, the work around was to not use optimistic rendering in this case.
